apiVersion: apps/v1
kind: Deployment
metadata:
  name: maven-app
spec:
  replicas: 2
  selector: 
   matchLabels:
     app: gitops-maven
  template:
    metadata:
      labels:
        app: gitops-maven
    spec: 
      containers:
        - name: maven-app
          image: reg.tlandino.net/maven-app:1.0.0
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080